### ISSUE TITLE
Illegal array key type URL campaign_fetch.php

### ISSUE THREAD

**Issue by etruel** [etruel/wpematico#10]
campaign_fetch.php (linea, col)

Cambiar por md5 ?

Error:(200, 21) Illegal array key type URL
Error:(204, 23) Illegal array key type URL
Error:(210, 32) Illegal array key type URL
Error:(211, 23) Illegal array key type URL
Error:(213, 32) Illegal array key type URL
Error:(213, 73) Illegal array key type URL
Error:(214, 42) Illegal array key type URL
Error:(216, 130) Illegal array key type URL
Error:(227, 38) Illegal array key type URL
Error:(228, 139) Illegal array key type URL
Error:(236, 127) Illegal array key type URL
Error:(267, 23) Illegal array key type URL
Error:(271, 37) Illegal array key type URL

**Comment by gerarjos14** [comment]
i can do it
