### ISSUE TITLE
Tools page design

### ISSUE THREAD

**Issue by manuelge** [etruel/wpematico#113]
The design of the Tools page needs to be improved, the same design line that is being worked on for the metaboxes needs to be added, for example, the heading with icon, and also add the help icons next to each feature.

**Comment by etruel** [comment]
We won't do the same design of the metaboxes.  I think we could put icon and bottom line for the title but nothing else.  Let's look for something simpler.  In the future the core settings will also change more like flash which is more intuitive.

**Comment by manuelge** [comment]
Fixed
