### ISSUE TITLE
Problems with permalink with &amp;

### ISSUE THREAD

**Issue by manuelge** [etruel/wpematico#136]
A user reported a issue with redirected links to Facebook posts coming from his feed
(private)

The problem seems to be related to the **&amp;** symbol, for example:

**NOT WORK:**
`https://www.facebook.com/permalink.php?id=100083687880755&amp;story_fbid=pfbid0oPFFbhMdi5xR9eYSPJZdTva2WQxcMphCecFvS79PEpFTuM6G7YMwi2WWK4V9J5GSl`

**WORK:**
`https://www.facebook.com/permalink.php?id=100083687880755&story_fbid=pfbid0oPFFbhMdi5xR9eYSPJZdTva2WQxcMphCecFvS79PEpFTuM6G7YMwi2WWK4V9J5GSl`

**Comment by etruel** [comment]
This was a redirection problem that could be solved with the option: Avoid follow redirections on permalink
