### ISSUE TITLE
error on line 658

### ISSUE THREAD

**Issue by diogenis1971** [etruel/wpematico#17]
Recoverable fatal error: Object of class WP_Error could not be converted to string in /home/phkmxjmy/public_html/wp-content/plugins/wpematico/app/campaigns_list.php on line 658

campaigns_list.php on line 658

<div class="campaign_categories">' . implode(',', $campaign_categories) . '</div> .... have this in line 658...

if delete the..this  implode(',', and this ) then put this messege

Notice: Array to string conversion in /home/phkmxjmy/public_html/wp-content/plugins/wpematico/app/campaigns_list.php on line 658

any help;

**Comment by asuajeivan** [comment]
Hi Sebastian Wörner,

Thank you very much for notifying us about this issue.

Please attach the debug file for the plugin.

You can find and download it from your Wordpress admin, WPeMatico, Settings, System Status tab ->Debug Info.

Yes you can include the campaign logs by checking the checkbox field before downloading the debug file.


Regards,
Iván

**Comment by asuajeivan** [comment]
Hi diogenis1971,

Thank you very much for notifying us about this issue.

Please attach the debug file for the plugin.

You can find and download it from your Wordpress admin, WPeMatico, Settings, System Status tab ->Debug Info.


Regards,
Iván

**Comment by etruel** [comment]
Hi @diogenis1971, 
That seems to be related to your php version, @asuajeivan ask for your debug file to see what php version are you using, but I've made some changes on that lines that should fix yours problems.  

Anyway I'll close the issue. Would be great if you can try it. 
cheers
