### ISSUE TITLE
Many features added in asana

### ISSUE THREAD

**Issue by etruel** [etruel/wpematico#29]
Agregar un banner para re ver la campaign en el wizard https://app.asana.com/0/0/584386200485226/f

Agregar Opciones checkbox para agregar el shortcode to show the audios at the end or beginning of the post. https://app.asana.com/0/0/1125443967661219/f

**Comment by Paul24011993** [comment]
The banner has been successfully added to be seen when editing the campaign.

**Comment by Paul24011993** [comment]
El shortcode creado en el "wpematico professional" para mostrar videos o audios en el post creado, presenta un problema ya que al existir mas de un audio o video en el feed siempre toma solo el primero y lo muestra descartando los demás, esto se debe principalmente a la versión actualmente instalada de la librería SimplePie sin embargo existen post que recomiendan como ultima opcion agregar un parche para trabajar con normalidad

**Comment by etruel** [comment]
El issue del shortcode se resuelve con [playlist] 
Hay que examinar como ejemplificarlo en los help del post template.
