### ISSUE TITLE
PHP 8.1.4  Warnings ***

### ISSUE THREAD

**Issue by etruel** [etruel/wpematico#30]
My php vesion is 8.1.4 and I have 256M PHP memory. Recently, I get the below warning messages.

PHP Warning: Undefined array key "activated" in public_html/wp-content/plugins/wpematico/app/cron_functions.php on line 31
PHP Warning: Undefined array key "cronnextrun" public_html/wp-content/plugins/wpematico/app/cron_functions.php on line 32

**Comment by Paul24011993** [comment]
the variables were initialized and the error was corrected.
