### ISSUE TITLE
wp-cli wrapper

### ISSUE THREAD

**Issue by w3rkzeug** [etruel/wpematico#39]
Hi there,
i'm trying to extend this plugin , and trying to build a wp-cli command that launches all the wpematico campaigns, if i run my command manually all works, but if i put it in a bash script for newly imported campaigns  then it doesn't...is there smth else to init before calling the dojob method ?
thanks..
![image](https://user-images.githubusercontent.com/40423351/168430152-a76206ae-88a6-423c-91a7-bef61b796089.png)

**Comment by etruel** [comment]
Hi @w3rkzeug 
Sorry just asking, Instead of adapt that code why not call from your scrip the url of the external cron ?

**Comment by w3rkzeug** [comment]
> Hi @w3rkzeug Sorry just asking, Instead of adapt that code why not call from your script the url of the external cron ?

Hi,
Can you  provide an example?not sure what is the url... definetly worth trying it,
thanks

**Comment by etruel** [comment]
yes, take a look at the Settings Page of the plugin inside WordPress. I think It will give you an idea on how to make the call from a script. 
![image](https://user-images.githubusercontent.com/3663229/168449859-5cd25c4a-37d6-41fe-ae86-772bd55cbac2.png)

**Comment by w3rkzeug** [comment]
hmm.. so i need to disable wpematico schedules, run the https://mysite.com/wp-admin/admin-post.php?action=wpematico_cron link and then turn it back on to follow the campaigns schedules right ? is there a specific method / code level to turn  it off/on?
thanks

**Comment by w3rkzeug** [comment]
So finally i've got the idea , the cli wrapper i made works if i login on the wp-admin panel .
All i do, login to wp-admin , then launch the wp cli command and it works, may be some init code ... not sure...

**Comment by etruel** [comment]
I'm not sure I understand, do you mean an init code to login automatically  ?
