### ISSUE TITLE
Allowed image extensions to upload

### ISSUE THREAD

**Issue by zelik888** [etruel/wpematico#43]
When grabbing images from RSS feeds, img tags that have a query string at the end cannot be uploaded as they are not in the allowed image extensions.

For example:
https://somewebsite.com/cs/0cf231f02cb964191c4f240e8/images/18bbc33e-ea69-d691-6bd6-96ee5660054c.png?w=258&dpr=2

Is there a way to exclude the query string to allow grabbing the images to upload to the post?

**Comment by manuelge** [comment]
Thanks for your interest.

That feature is included and optimized in the [Professional](https://etruel.com/downloads/wpematico-professional/) addon, you may want to take a look at it to know all its features.

But there is another free option although it requires some technical knowledge, you will find it in [this](https://www.wpematico.com/set-images-featured-wpematico/) article, there is information about featured images and how to get them, you can also find a **filter** that allows you to remove the queries variables from the URL of the images before getting them. 

I hope you find this information useful and don't forget to check our [extensions for WPeMatico](https://etruel.com/downloads/category/wpematico-add-ons/). 

Cheers,
Manuel

**Comment by zelik888** [comment]
Thank you, I couldn't find information on what addon to purchase.
