### ISSUE TITLE
Deprecated 8.1+

### ISSUE THREAD

**Issue by manuelge** [etruel/wpematico#44]
Deprecated: Automatic conversion of false to array is deprecated in C:\Users\Manuel Gutierrez\Local Sites\php8-wp\app\public\wp-content\plugins\wpematico\app\wpematico_functions.php on line 1618

**Comment by etruel** [comment]
https://github.com/etruel/wpematico/blob/f530451745e31cb0baa8994c517179a15b86a22b/app/wpematico_functions.php#L1618
