### ISSUE TITLE
Featured image no fetching in website post 

### ISSUE THREAD

**Issue by Mauricce** [etruel/wpematico#45]
No featured images is fetch in website. Here is few links of website post and original feed

Website post URL : https://jimmyreedblues.wpengine.com/steve-hill-releases-dont-let-the-truth-get-in-the-way-of-a-good-story-video/
Original URL : https://bluesrockreview.com/2022/11/steve-hill-releases-dont-let-the-truth-get-in-the-way-of-a-good-story-video.html?utm_source=rss&utm_medium=rss&utm_campaign=steve-hill-releases-dont-let-the-truth-get-in-the-way-of-a-good-story-video

Website post URL : https://jimmyreedblues.wpengine.com/grace-bernickers-new-soothing-soulful-song-feels-like-home/
Original URL : https://www.americanbluesscene.com/2022/11/grace-bernickers-new-soothing-soulful-song-feels-like-home/?utm_source=rss&utm_medium=rss&utm_campaign=grace-bernickers-new-soothing-soulful-song-feels-like-home

Can you please help me to find exact issue for this.

**Comment by etruel** [comment]
Hi @Mauricce, this is not an issue.
No matter source site.  You should check the source of the feed.  It depends entirely of the contents in the feed used in the campaign.  

If you need help to solve it,  create a support Ticket in the [website](https://etruel.com/my-account/support/) and attach the Debug File from the plugin in the ticket (It's a free service ;-) ).

You can find the debug file and download from your WordPress admin-> WPeMatico-> Settings, Debug Info Tab

​Cheers​
​etruel
