### ISSUE TITLE
YouTube Fetcher Campaign Type - DEPRECATED logs

### ISSUE THREAD

**Issue by manuelge** [etruel/wpematico#49]
A user who is using **PHP version 8.1.17** reported some PHP DEPRECATED when running the campaign.

I was doing some tests with the highest version of PHP I have 8.1.9 and they were not generated.

[DEPRECATED] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
[DEPRECATED] stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated
[DEPRECATED] preg_match_all(): Passing null to parameter #2 ($subject) of type string is deprecated
[DEPRECATED] str_ireplace(): Passing null to parameter #3 ($subject) of type array|string is deprecated

I also want to clarify that the user is using the "Featured Image From URL" plugin that runs along with the campaign, so it is possible that some of those DEPRECATED are from that plugin.

**Comment by gerarjos14** [comment]
Can't reproduce the problem. We would need more data. But seems to be a local problem of the user.
