### ISSUE TITLE
PHP Fatal error | get_favicon()

### ISSUE THREAD

**Issue by manuelge** [etruel/wpematico#53]
A user gets a fatal error when trying to execute the XML campaign type.

I was running several tests to try to replicate the problem but could not generate it.

PHP Fatal error: Uncaught Error: Call to undefined method WPeMatico_SimplePie::get_favicon() in /www/wwwroot/pingtungtimes/wp-content/plugins/wpematico/app/campaign_fetch_functions.php:203
Stack trace:
#0 /www/wwwroot/pingtungtimes/wp-content/plugins/wpematico/app/campaign_fetch_functions.php(135): wpematico_campaign_fetch_functions::default_template_vars()
#1 /www/wwwroot/pingtungtimes/wp-includes/class-wp-hook.php(303): wpematico_campaign_fetch_functions::wpematico_template_parse()
#2 /www/wwwroot/pingtungtimes/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#3 /www/wwwroot/pingtungtimes/wp-content/plugins/wpematico/app/campaign_fetch_functions.php(87): apply_filters()
#4 /www/wwwroot/pingtungtimes/wp-content/plugins/wpematico/app/campaign_fetch.php(441): wpematico_campaign_fetch_functions->Item_parsers()
#5 /www/wwwroot/pingtungtimes/wp-content/plugins/wpematico/app/campaign_fetch.php(276): wpematico_campaign_fetch->processItem()
#6 /www/wwwroot/pingtungtimes/wp-content/plugins/wpematico/app/campaign_fetch.php(114): in /www/wwwroot/pingtungtimes/wp-content/plugins/wpematico/app/campaign_fetch_functions.php on line 203

**Comment by etruel** [comment]
Fixed on 2.6.20.2 Jul 21, 2023
