### ISSUE TITLE
Fatal Error with Force SimplePie + Use feed item date

### ISSUE THREAD

**Issue by manuelge** [etruel/wpematico#55]
**PHP Deprecated:**  Required parameter $working follows optional parameter $type in C:\xampp\htdocs\wordpress\wp-content\plugins\wpematico\app\lib\SimplePie\Locator.php on line 93

**PHP Fatal error:**  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in C:\xampp\htdocs\wordpress\wp-content\plugins\wpematico\app\lib\SimplePie\Parse\Date.php:544
Stack trace:
#0 C:\xampp\htdocs\wordpress\wp-content\plugins\wpematico\app\lib\SimplePie\Parse\Date.php(544): implode(Array, '|')
#1 C:\xampp\htdocs\wordpress\wp-content\plugins\wpematico\app\lib\SimplePie\Parse\Date.php(577): SimplePie_Parse_Date->__construct()
#2 C:\xampp\htdocs\wordpress\wp-content\plugins\wpematico\app\lib\SimplePie\Registry.php(221): SimplePie_Parse_Date::get()
#3 C:\xampp\htdocs\wordpress\wp-content\plugins\wpematico\app\lib\SimplePie\Item.php(805): SimplePie_Registry->call('Parse_Date', 'get')
#4 C:\xampp\htdocs\wordpress\wp-content\plugins\wpematico\app\campaign_fetch.php(322): SimplePie_Item->get_date('U')
#5 C:\xampp\htdocs\wordpress\wp-content\plugins\wpematico\app\campaign_fetch.php(276): wpematico_campaign_fetch->processItem(Object(SimplePie), Object(SimplePie_Item), 'http://counselo...')
#6 C:\xampp\htdocs\wordpress\wp-content\plugins\wpematico\app\campaign_fetch.php(114): wpematico_campaign_fetch->processFeed('http://counselo...', 0)
#7 C:\xampp\htdocs\wordpress\wp-content\plugins\wpematico\app\wpematico_functions.php(1096): wpematico_campaign_fetch->__construct(1878)
#8 C:\xampp\htdocs\wordpress\wp-content\plugins\wpematico\app\campaign_edit.php(191): WPeMatico_functions::wpematico_dojob(1878)
#9 C:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(308): WPeMatico_Campaign_edit->RunNowX('')
#10 C:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#11 C:\xampp\htdocs\wordpress\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#12 C:\xampp\htdocs\wordpress\wp-admin\admin-ajax.php(188): do_action('wp_ajax_wpemati...')
#13 {main}
  thrown in C:\xampp\htdocs\wordpress\wp-content\plugins\wpematico\app\lib\SimplePie\Parse\Date.php on line 544

**Comment by etruel** [comment]
This error should be fixed on remove custom Simplepie [issue](https://github.com/etruel/wpematico/issues/56) https://github.com/etruel/wpematico/issues/56
