### ISSUE TITLE
Css issue on settings

### ISSUE THREAD

**Issue by etruel** [etruel/wpematico#64]
On Settings at bottom:
User roles to show Dashboard widget:
Has an scrollbar but the left for Empty Trash button doesn't.  (See image) 
Should take a better design for this. 

<img width="685" alt="image" src="https://github.com/etruel/wpematico/assets/3663229/c64eee8a-8600-41b2-88e5-82d081268eb7">

**Comment by Mstanic05** [comment]
Can you assign this to me!

**Comment by etruel** [comment]
Hi. You can fork the repo and make pull request when you finish.

**Comment by etruel** [comment]
Hi @Mstanic05 
if we do not hear back from you in the next few hours the ticket will be reassigned. 
Thank you

**Comment by manuelge** [comment]
corrected, adjusted the styles to give an equal size to both, and also modified the responsive.
