### ISSUE TITLE
New logs to individual posts on WPeMatico website. 

### ISSUE THREAD

**Issue by etruel** [etruel/wpematico#65]
The plugin CF7 shows the changelog as in the image below.  We'll follow this method in the future since this milestone 2.7. 

- [ ] So we could start from 2.6 version and each subversion and we'll need to make a post in the website for each one in the changeling on readme.txt. 

- [ ] After that change in readme.txt for each permalink like CF7, but with the version number and the date too. 

<img width="1115" alt="image" src="https://github.com/etruel/wpematico/assets/3663229/aac31d2b-a17d-4b2c-b38b-09f8f80d508b">

**Comment by manuelge** [comment]
Done, each log since 2.6 version was created as a post in [https://wpematico.com/releases/](https://www.wpematico.com/releases/).
