### ISSUE TITLE
Add SimplePie Version on System Status 

### ISSUE THREAD

**Issue by etruel** [etruel/wpematico#73]
Add the version of SIMPLEPIE used by the WordPress that we removed from settings 
![image](https://github.com/etruel/wpematico/assets/3663229/abbe3cc5-4dc5-4205-aa8e-35db3caf6b82)

Make sure it is added both to the export file and on screen.  Minimum version required is 1.5.1.  Add the help tip and look at the other variables to have the same behavior with the notices. 
![image](https://github.com/etruel/wpematico/assets/3663229/8466dfb3-17b5-4042-9966-5f0aed3c11d4)

**Comment by gerarjos14** [comment]
It's already added
