### ISSUE TITLE
Fatal error in the "Fill Excerpt" feature when the <description> tag is empty or does not exist.

### ISSUE THREAD

**Issue by manuelge** [etruel/wpematico#74]
When the <description> tag of the feed is empty or does not exist this error is generated, in this case the error was generated when using a YouTube feed.

WordPress database error Column 'post_excerpt' cannot be null for query INSERT INTO `wp_posts` (`post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_content_filtered`, `post_title`, `post_excerpt`, `post_status`, `post_type`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_parent`, `menu_order`, `post_mime_type`, `guid`) VALUES (1, '2023-11-22 15:32:15', '2023-11-22 15:32:15', ' [embed]https://www.youtube.com/watch?v=NzeOJ8e-wnk[/embed] <p>İnfo Yatırım’da Hesap Açarak hem Piyasaları 15 Dakika Gecikmeli Değil Anlık Takip Edin hem de Yatırım Hesabınız ile TradingView Hesabınızı ile entegre ederek TradingView Web ve Mobil Uygulaması Üzerinden İşlem Yapmaya Başlayın! \n\n🔗 https://infoytrm.com/beinsports\n\nTürkiye Sigorta Basketbol Süper Ligi\'nde 8. haftasında yapılan top 5 hareket sizlerle... \n\nbeIN SPORTS\'un en güncel programlarını, spor dolu içeriklerini takip etmek için kanala abone olmayı unutmayın: http://dgtrk.lu/1ebhi\n\n--------------\n\nbeIN SPORTS Arşiv: http://dgtrk.lu/1evqg\n\n--------------\n\nBizi sosyal medyada takip edin: \n📌 Facebook: https://www.facebook.com/beINSPORTSTR \n📌 Twitter: https://twitter.com/beINSPORTS_TR \n📌 Instagram: https://www.instagram.com/beinsportstr/\n\n--------------\n\n#türkiyebasketbolsüperligi #basketbol #eniyihareketler #top5</p>', ' [embed]https://www.youtube.com/watch?v=NzeOJ8e-wnk[/embed] <p>İnfo Yatırım’da Hesap Açarak hem Piyasaları 15 Dakika Gecikmeli Değil Anlık Takip Edin hem de Yatırım Hesabınız ile TradingView Hesabınızı ile entegre ederek TradingView Web ve Mobil Uygulaması Üzerinden İşlem Yapmaya Başlayın! \n\n🔗 https://infoytrm.com/beinsports\n\nTürkiye Sigorta Basketbol Süper Ligi\'nde 8. haftasında yapılan top 5 hareket sizlerle... \n\nbeIN SPORTS\'un en güncel programlarını, spor dolu içeriklerini takip etmek için kanala abone olmayı unutmayın: http://dgtrk.lu/1ebhi\n\n--------------\n\nbeIN SPORTS Arşiv: http://dgtrk.lu/1evqg\n\n--------------\n\nBizi sosyal medyada takip edin: \n📌 Facebook: https://www.facebook.com/beINSPORTSTR \n📌 Twitter: https://twitter.com/beINSPORTS_TR \n📌 Instagram: https://www.instagram.com/beinsportstr/\n\n--------------\n\n#türkiyebasketbolsüperligi #basketbol #eniyihareketler #top5</p>', 'İnfo Yatırım | Türkiye Sigorta Basketbol Süper Ligi 8. Hafta | Top 5 Hareket', NULL, 'publish', 'post', 'closed', 'closed', '', 'info-yatirim-turkiye-sigorta-basketbol-super-ligi-8-hafta-top-5-hareket', '', '', '2023-11-22 15:32:15', '2023-11-22 15:32:15', 0, 0, '', '') made by do_action('wp_ajax_wpematico_run'), WP_Hook->do_action, WP_Hook->apply_filters, WPeMatico_Campaign_edit->RunNowX, WPeMatico_functions::wpematico_dojob, wpematico_campaign_fetch->__construct, wpematico_campaign_fetch->processFeed, wpematico_campaign_fetch->processItem, wp_insert_post

**Comment by gerarjos14** [comment]
Fixed
