### ISSUE TITLE
Fix styles Quick Add category

### ISSUE THREAD

**Issue by etruel** [etruel/wpematico#9]
Cuando se hace una Quick Add de categoria en la campaña se ve mal el estilo.  

![Firefox_Screenshot_2020-11-20T17-13-11 379Z](https://user-images.githubusercontent.com/3663229/99829257-d49ba600-2b3a-11eb-83ac-9f2355e31210.png)

**Comment by manuelge** [comment]
Vale amigo, puedes agregar estos css al style de wpematico, no lo hice yo porque no se si estás editando algo, pruebalo y me avisas.

#category-box #categories li{
	display: flex;
	align-items: center;
}
#category-box #categories li input[type="checkbox"]{
	margin-right: .5rem;
}

**Comment by etruel** [comment]
Amigo no me funciona, lo probé en varios lugares y no cambia.  Modifica el archivo y subilo. Si estoy editando algo te aviso antes.
